# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

SLAVES = 1
#slave_hash = {}
slave_hostnames = []
slave_ips = []

(1..SLAVES).each do |slave|
  slave_hostnames.push("mesos-slave-#{slave}")
  slave_ips.push("44.44.44.1#{slave}")
  #slave_hash["mesos-slave-#{slave}"] = "44.44.44.1#{slave}"
end

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "mesos-master" do |mm|
    mm.vm.network "private_network", ip: "44.44.44.10"
    mm.vm.hostname = "mesos-master"
    mm.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "2048"
    end
    # Provision using Ansible playbook
    mm.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/master_main.yaml"
      ansible.extra_vars = {
        "slave_hostnames" => "#{slave_hostnames}",
        "slave_ips" => "#{slave_ips}"
      }
      #ansible.extra_vars = {
      #  "slave_hostnames" => "#{slave_hash}"
      #}
    end
  end

  (1..SLAVES).each do |slave|
    config.vm.define "mesos-slave-#{slave}" do |ms|
      ms.vm.network "private_network", ip: "44.44.44.1#{slave}"
      ms.vm.hostname = "mesos-slave-#{slave}"
      ms.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
      end
      ms.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          master_hostname: "mesos-master",
          master_ip: "44.44.44.10"
        }
        ansible.playbook = "playbooks/slave_main.yaml"
      end
    end
  end
end
